/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-05-29 13:07:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Flight Search</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("input[type=text] {\r\n");
      out.write("    background-color: #1A2226;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-bottom: 2px solid #0DB8DE;\r\n");
      out.write("    border-top: 0px;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    padding-left: 0px;\r\n");
      out.write("    color: #ECF0F5;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("input[type=password] {\r\n");
      out.write("    background-color: #1A2226;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-bottom: 2px solid #0DB8DE;\r\n");
      out.write("    border-top: 0px;\r\n");
      out.write("    border-radius: 0px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    outline: 0;\r\n");
      out.write("    padding-left: 0px;\r\n");
      out.write("    margin-bottom: 20px;\r\n");
      out.write("    color: #ECF0F5;\r\n");
      out.write("}\r\n");
      out.write(".login-title {\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	font-size: 30px;\r\n");
      out.write("	letter-spacing: 2px;\r\n");
      out.write("	margin-top: 15px;\r\n");
      out.write("	font-weight: bold;\r\n");
      out.write("	color: #ECF0F5;\r\n");
      out.write("}\r\n");
      out.write(".login-box {\r\n");
      out.write("	margin-top: 75px;\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background-color: #1A2226;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	box-shadow: 0 3px 6px rgba(0, 0, 0, 0.16), 0 3px 6px rgba(0, 0, 0, 0.23);\r\n");
      out.write("}</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #222D32;font-size: 10px;\r\n");
      out.write("	color: #6C6C6C;	font-weight: bold;letter-spacing: 1px;\">\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"container mt-5 mx-auto\">\r\n");
      out.write("		<div class=\"row\">\r\n");
      out.write("			<div class=\"col-lg pl-2 login-box\"\r\n");
      out.write(">\r\n");
      out.write("				<div class=\"col-lg-12 login-title text-center\">USER PANEL</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"row\" style=\"background-color: #1A2226;\">\r\n");
      out.write("			<form action=\"login\" method=\"post\"\r\n");
      out.write("				class=\"col-sm-12 col-lg-12 col-md-12 mt-3 pl-2\">\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label for=\"Name\" class=\"col-sm-2 col-lg-3 col-form-label\">Username:</label>\r\n");
      out.write("					<label style=\"color: red;\">*</label>\r\n");
      out.write("					<div class=\"col-sm-6 col-md-8 col-lg-5\">\r\n");
      out.write("						<input type=\"text\" required class=\"form-control\"\r\n");
      out.write("							style=\"height: 30px; border-radius: 0px;\" name=\"unm\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label for=\"Email\" class=\"col-sm-2 col-lg-3 col-form-label\">Password:</label>\r\n");
      out.write("					<label style=\"color: red;\">*</label>\r\n");
      out.write("					<div class=\"col-sm-6 col-md-8 col-lg-5\">\r\n");
      out.write("						<input type=\"password\" required class=\"form-control\"\r\n");
      out.write("							style=\"height: 30px; border-radius: 0px;\" name=\"pass\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<span class=\"font-weight-bold text-danger\"> ");

 					if (session.getAttribute("error") != null) {
 					
      out.write(' ');
      out.print(session.getAttribute("error"));
      out.write(' ');

 					session.setAttribute("error", null);
 					}
					 
      out.write("\r\n");
      out.write("				</span>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label for=\"Email\" class=\"col-sm-2 col-lg-3 col-form-label\"></label>\r\n");
      out.write("					<div class=\"col-sm-6 col-md-8 col-lg-6\">\r\n");
      out.write("						<a href=\"forgotpassword\">Forgot password?</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row\">\r\n");
      out.write("					<label for=\"Email\" class=\"col-sm-2 col-lg-3 col-form-label\"></label>\r\n");
      out.write("					<div class=\"col-sm-6 col-md-8 col-lg-6\">\r\n");
      out.write("						<a href=\"signup\">New User</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group row mb-0\">\r\n");
      out.write("					<div class=\"col-lg d-flex flex-row-reverse p-1 ml-2\"\r\n");
      out.write("						style=\"background-color: #1A2226;\">\r\n");
      out.write("						<input class=\"btn btn-primary pt-0 pr-3 pl-3\" type=\"submit\"\r\n");
      out.write("							value=\"Login &#187;\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
